apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: poc-ci-claim2
  name: poc-ci-claim2
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-default"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
status: {}
