apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: poc-ci-nginx
  name: poc-ci-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: poc-ci-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: poc-ci-nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html:ro
          name: poc-ci-claim2
      restartPolicy: Always
      volumes:
      - name: poc-ci-claim2
        persistentVolumeClaim:
          claimName: poc-ci-claim2
status: {}