apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: poc-ci-claim0
  name: poc-ci-claim0
  annotations:
    volume.beta.kubernetes.io/storage-class: "cstor-disk-pool-default"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
