apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: poc-ci
  name: poc-ci
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: poc-ci
    spec:
      containers:
      - image: enyachoke/poc-ci
        imagePullPolicy: Always
        name: poc-ci
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/bin/deploy-scripts
          name: poc-ci-claim0
        - mountPath: /tmp/keys
          name: poc-ci-claim1
        - mountPath: /opt/testbuilds/
          name: poc-ci-claim2
      restartPolicy: Always
      volumes:
      - name: poc-ci-claim0
        persistentVolumeClaim:
          claimName: poc-ci-claim0
      - name: poc-ci-claim1
        persistentVolumeClaim:
          claimName: poc-ci-claim1
      - name: poc-ci-claim2
        persistentVolumeClaim:
          claimName: poc-ci-claim2
status: {}
